### ISSUE TITLE
cloneAll.sh only works if you have commit access

### ISSUE THREAD

**Issue by paperdigits** [dita4publishers/dita4publishers#4]
Not sure if this is the intention, but the script cloneAll.sh only works if you have commit access to the repos.

**Comment by blefort** [comment]
Is it that it only works if you have commit access to the repos or when you have a ssh key set-up in your account?

**Comment by drmacro** [comment]
It definitely requires ssh setup--it shouldn't require commit access. 

submoduleAll.sh uses the https form of URL.

**Comment by blefort** [comment]
I'd like to keep it like it is. I always work using ssh access.

**Comment by drmacro** [comment]
I don't see a need to change it. I created submoduleAll.sh as an alternative when ssh access is not set up (I only just now got it set up for myself)

**Comment by paperdigits** [comment]
I'm not sure if it is ssh or commit access, but the repo URL changes if you're logged in or not logged in.

**Comment by blefort-uo** [comment]
Logged in: both ssh and https are available, ssh is preferred. ssh requires an account and a key to authentifie;
git@github.com:dita4publishers/dita4publishers.git
https://github.com/dita4publishers/dita4publishers.git

Logged out, only https is available, i think this is because no authentification is required for https on a public repo:
https://github.com/dita4publishers/dita4publishers.git

**Comment by blefort-uo** [comment]
Mica, do you think it is ok if I close the issue?

**Comment by paperdigits** [comment]
Yes, it is OK to close this. If people without shell/login access want to get everything, they should clone with the --recursive option.
