### ISSUE TITLE
Travis test for DITA_OT 2.0 failed

### ISSUE THREAD

**Issue by blefort** [dita4publishers/dita4publishers#9]
Even if the Travis return success, which is strange
```
Calling command DITA-OT2.0/test/bin/test_all.sh...
Running HTML5 transform on complex_map:
Error: Target "move-links" does not exist in the project "DOST". It is used from target "dc-preprocess".
Running EPUB transform on complex_map:
Error: Target "move-links" does not exist in the project "DOST". It is used from target "dc-preprocess".
Done
```

**Comment by drmacro** [comment]
Yes, I need to look at the dita script in 2.0 to see why it's not reporting a failure in that case.

**Comment by drmacro** [comment]
I have worked out how to correctly capture and return the result codes from the scripts that are running the tests so that failures are correctly reported. The key is capturing the result codes, accumulating them, and then returning that as the result of the test_all.sh script. Shell scripts return as their return code whatever the return code of the last command was, so if the last like is "echo Done" then the return code will be zero from the echo command.

**Comment by blefort-uo** [comment]
Interesting. Thank you for having fixed this, I think Travis is a very handy tool when it is time to test our code !

**Comment by trichard** [comment]
Hi,
I've got exactly this issue when running epub transformation on a map with latest git repos. How to fix it ? If it was fixed then it is not yet committed, is it?

**Comment by blefort** [comment]
Which version of the OT are you using?

**Comment by trichard** [comment]
Latest one: v2.0.1

**Comment by blefort** [comment]
The move to 2.x is not completed yet in my knowledge
